### PR TITLE
Add ERD diagram image

### PR DESCRIPTION
**Pull request by AbdumurodovaZulfizar**
### Milestone One
Requirements:

- Create your own ERD. You can use an online tool to do that or draw it on a piece of paper and take a photo of it.
- Think about friendship and friendship requests. Small hint: try to use the status of the friendship to tell if it is a request or confirmed friendship.
- Extra hint: keep profile image as a link to gravatar as storing files is a bit tricky in Heroku.
- Put a file with your ERD in the “docs” directory in your repo.

by Zulfizar Abdumurodova(Full-Stuck Software developer)

### CODE REVIEW

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUIRED🛑️🛑️🛑️🛑️**

Hello @AbdumurodovaZulfizar 
Great work on this milestone. However, let's make a small change.

[REQUIRED]: use tools like lucidchart to draw the ERD instead of drawing it manually.

That's it.

Make the required changes and ask for another review👍️👍️👍️

Happy coding💻️💻️💻️

**Comment by AbdumurodovaZulfizar** [comment]
Is it not optional?

**Review by oloomoses — CHANGES_REQUESTED** [review]
## Changes Required
**Hello @AbdumurodovaZulfizar, your ERD is impressive :clap:
Below are some of the issues to fix :point_down:**

- [ ] The relationship between a User and friendship table should look like this:
u

Kindly implement the above changes before submitting another code review.
### Feel free to leave a comment :point_down: while mentioning me. I will be happy to reply
## HAPPY CODING 
_Slack: Oloo Moses_

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

**Pull request merged**
